#ifndef TONETRACE_CLAP_RESOURCE_H_
#define TONETRACE_CLAP_RESOURCE_H_

#define IDD_TONETRACE_EDITOR 101
#define IDD_TONETRACE_OPTIONS 102

#define IDC_OPTION_FULL_CORRECTION 1100
#define IDC_OPTION_TONE_NOTIFICATIONS 1101
#define IDC_OPTION_TONE_LEVEL_LABEL 1102
#define IDC_OPTION_TONE_LEVEL 1103
#define IDC_OPTION_BYPASS 1104
#define IDC_OPTION_RESET 1105

#endif
