#ifndef TONETRACE_CLAP_RESOURCE_H_
#define TONETRACE_CLAP_RESOURCE_H_

#define IDD_TONETRACE_EDITOR 101
#define IDD_TONETRACE_OPTIONS 102

#define IDC_OPTION_FULL_RANGE 4001
#define IDC_OPTION_TONE_NOTIFICATIONS 4002
#define IDC_OPTION_TONE_LEVEL 4003
#define IDC_OPTION_BYPASS 4004
#define IDC_OPTION_RESET 4005

#endif
